# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: javiersorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: follow
service: my-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
